name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Publish binaries
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Build
      id: build
      run: |
        cargo build --release
        $file_version = (Get-Item ./target/release/cncr.exe).VersionInfo.FileVersion
        "VERSION=$file_version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
    - name: Upload binaries to release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/release/cncr.exe
          target/release/cnctt.exe
        tag_name: ${{ steps.build.outputs.VERSION }}
        body: "release"
        overwrite: true
