name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Publish binaries
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cargo build --release
        $file_version = (Get-Item ./target/release/cncr.exe).VersionInfo.FileVersion
        echo "Version: $file_version"
        echo "VERSION=$file_version" >> "$GITHUB_ENV"
        echo "VERSION is set to $file_version"
        echo "env.VERSION is set to ${{env.VERSION}}"
      shell: powershell
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/cncr.exe
        asset_name: cncr.exe
        tag: ${{ github.ref }}
        overwrite: true
        body: "update"
