name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Publish binaries
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      id: build
      run: |
        cargo build --release
        $file_version = (Get-Item ./target/release/cncr.exe).VersionInfo.FileVersion
        echo "Version: $file_version"
        echo "VERSION=$file_version" >> "$GITHUB_OUTPUT"
      shell: powershell
    - name: Get version
      env:
        FILE_VERSION: ${{ steps.build.outputs.VERSION }}
      run: echo "Version is $FILE_VERSION"
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/cncr.exe
        asset_name: cncr.exe
        tag: ${{ env.FILE_VERSION }}
        overwrite: true
        body: "lastest"
